# Generated by Django 3.2.4 on 2021-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0004_alter_review_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='favorited',
            field=models.ManyToManyField(related_name='favorited_review', to='reviewapp.User'),
        ),
    ]
